options = 
{
	{ 
		default = 0, 
		label = "Game Mode", 
		help = "Game Mode", 
		key = 'opt_gamemode', 
		pref = 'opt_gamemode',
		values = { 
			{text = "Normal", help = "Normal", key = 0, }, 
			{text = "Paragon Wars", help = "Paragon Wars", key = 1, },
			{text = "Survival Versus", help = "Survival Versus", key = 2, },
			{text = "Survival Easy", help = "Survival Easy", key = 3, },
			{text = "Survival Normal", help = "Survival Standard", key = 4, },
			{text = "Survival Hard", help = "Survival Hard", key = 5, },
			{text = "Survival Insane", help = "Survival Insane", key = 6, },
		}, 
	},
	{ 
		default = 0, 
		label = "Prebuilt Tents", 
		help = "Disable or Set the number of Prebuilt Engineering Tents", 
		key = 'opt_tents', 
		pref = 'opt_tents', 
		values = { 
			{text = "Disabled", help = "Spawn with NO tents", key = 0, }, 
			{text = "1", help = "Spawn with ONE tents", key = 1, }, 
			{text = "2", help = "Spawn with TWO tents", key = 2, }, 
			{text = "3", help = "Spawn with THREE tents", key = 3, }, 
			{text = "4", help = "Spawn with FOUR tents", key = 4, }, 
			{text = "5", help = "Spawn with FIVE tents", key = 5, }, 
			{text = "6", help = "Spawn with SIX tents", key = 6, }, 
			{text = "7", help = "Spawn with SEVEN tents", key = 7, }, 
			{text = "8", help = "Spawn with EIGHT tents", key = 8, }, 
			{text = "9", help = "Spawn with NINE tents", key = 9, }, 
		}, 
	}, 
	{
		default = 0, 
		label = "Auto Reclaim", 
		help = "AutoReclaim.", 
		key = 'opt_AutoReclaim', 
		pref = 'opt_AutoReclaim',
		values = { 
			{text = "Disabled (Wreckages On)", help = "Off", key = 0, }, 
			{text = "Auto Reclaim 10 percent", help = "10 percent", key = 1, },
			{text = "Auto Reclaim 15 percent", help = "15 percent", key = 2, },
			{text = "Auto Reclaim 20 percent", help = "20 percent", key = 3, },
			{text = "Auto Reclaim 30 percent", help = "30 percent", key = 4, },
			{text = "Auto Reclaim 40 percent", help = "40 percent", key = 5, },
			{text = "Auto Reclaim 50 percent", help = "50 percent", key = 6, },
		}, 
	},
	{ 
		default = 0, 
		label = "Air scouts and transports", 
		help = "Air is disabled. This option allows enabling just scouts and transports.",
		key = 'opt_transcount', 
		pref = 'opt_transcount',
		values = { 
			{text = "Disabled", help = "Disabled", key = 0, }, 
			{text = "Enabled", help = "Enabled", key = 1, }, 
		}, 
	}, 
	
	{ 
		default = 0, 
		label = "Player teleportation", 
		help = "Player teleportation", 
		key = 'opt_Teleport', 
		pref = 'opt_Teleport',
		values = { 
			{text = "Enabled", help = "Enabled", key = 0, }, 
			{text = "Disabled", help = "Disabled", key = 1, },
		}, 
	}, 
	{ 
		default = 0, 
		label = "Tech by Time", 
		help = "Players start with only tech 1. Higher tech tiers get unlocked at the specified interval. This does not effect the spawned enemy units.", 
		key = 'opt_timeunlocked', 
		pref = 'opt_timeunlocked',
		values = { 
			{text = "Disabled", help = "Disabled", key = 0, }, 
			{text = "5 Mins", help = "5 Mins", key = 1, },
			{text = "10 Mins", help = "10 Mins", key = 2, },
			{text = "15 Mins", help = "15 Mins", key = 3, },
			{text = "20 Mins", help = "20 Mins", key = 4, },
		}, 
	},
	{ 
		default = 0, 
		label = "T2 MMLs", 
		help = "T2 MMLs", 
		key = 'opt_t2tml', 
		pref = 'opt_t2tml',
		values = { 
			{text = "Enabled", help = "Enabled", key = 0, }, 
			{text = "Disabled", help = "Disabled", key = 1, },
		}, 
	},
	{ 
		default = 0, 
		label = "Mobile T3 artillery", 
		help = "Mobile T3 artillery", 
		key = 'opt_t3arty', 
		pref = 'opt_t3arty',
		values = { 
			{text = "Enabled", help = "Disabled", key = 0, }, 
			{text = "Disabled", help = "Disabled", key = 1, },
		}, 
	},
	{ 
		default = 0, 
		label = "Sniper bots", 
		help = "Sniper bots.", 
		key = 'opt_snipers', 
		pref = 'opt_snipers',
		values = { 
			{text = "Enabled", help = "Disabled", key = 0, }, 
			{text = "Disabled", help = "Disabled", key = 1, },
		}, 
	},
};