options =
{
    {
        default = 4,
        label = "Survival Difficulty",
        help = "Survival Difficulty. Affects both survival modes. Typical games should use Easier up to Harder depending on the skill level and the desired ability to harass the other team",
        key = 'opt_FinalRushDifficulty',
        pref = 'opt_FinalRushDifficulty',
        values = {
            { text = "Very easy", help = "Very easy", key = 1 },
            { text = "Easier", help = "Easier", key = 2 },
            { text = "Easy", help = "Easy", key = 3 },
            { text = "Normal", help = "Normal", key = 4 },
            { text = "Hard", help = "Hard", key = 5 },
            { text = "Harder", help = "Harder", key = 6 },
            { text = "Very hard", help = "Very hard. Not suitable to play without mods that make it easier", key = 7 },
            { text = "Insane", help = "Insane. Not suitable to play without mods that make it easier", key = 8 },
        },
    },
    {
        default = 1,
        label = "Escalation Speed",
        help = "(Survival modes only) How fast the game escalates to higher tier survival units",
        key = 'opt_FinalRushEscalationSpeed',
        pref = 'opt_FinalRushEscalationSpeed',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "1 minute per stage", help = "1 minute per stage", key = 60, },
            { text = "3 minutes per stage", help = "3 minutes per stage", key = 180, },
            { text = "4 minutes per stage (fast)", help = "4 minutes per stage (fast)", key = 240, },
            { text = "5 minutes per stage", help = "5 minutes per stage", key = 300, },
            { text = "5.5 minutes per stage", help = "5.5 minutes per stage", key = 330, },
            { text = "6 minutes per stage (standard)", help = "6 minutes per stage (standard)", key = 360, },
            { text = "6.5 minutes per stage", help = "6.5 minutes per stage", key = 390, },
            { text = "7 minutes per stage", help = "7 minutes per stage", key = 7 * 60, },
            { text = "8 minutes per stage (slow)", help = "8 minutes per stage (slow)", key = 8 * 60, },
            { text = "9 minutes per stage", help = "9 minutes per stage", key = 9 * 60, },
            { text = "10 minutes per stage", help = "10 minutes per stage", key = 600, },
        },
    },
    {
        default = 1,
        label = "Unit Amount",
        help = "(Survival modes only) How many enemy units should spawn",
        key = 'opt_FinalRushUnitCount',
        pref = 'opt_FinalRushUnitCount',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "25 percent", help = "25 percent", key = 0.25, },
            { text = "50 percent", help = "50 percent", key = 0.50, },
            { text = "60 percent", help = "60 percent", key = 0.60, },
            { text = "70 percent", help = "70 percent", key = 0.70, },
            { text = "80 percent (low)", help = "80 percent (low)", key = 0.80, },
            { text = "85 percent", help = "85 percent", key = 0.85, },
            { text = "90 percent", help = "90 percent", key = 0.90, },
            { text = "95 percent", help = "95 percent", key = 0.95, },
            { text = "100 percent (standard)", help = "100 percent (standard)", key = 1, },
            { text = "105 percent", help = "105 percent", key = 1.05, },
            { text = "110 percent", help = "110 percent", key = 1.1, },
            { text = "115 percent", help = "115 percent", key = 1.15, },
            { text = "120 percent (high)", help = "120 percent (high)", key = 1.20, },
            { text = "130 percent", help = "130 percent", key = 1.3, },
            { text = "140 percent", help = "140 percent", key = 1.4, },
            { text = "150 percent", help = "150 percent", key = 1.5, },
            { text = "175 percent", help = "175 percent", key = 1.75, },
            { text = "200 percent", help = "200 percent", key = 2, },
            { text = "250 percent", help = "250 percent", key = 2.5, },
            { text = "300 percent", help = "300 percent", key = 3, },
            { text = "400 percent", help = "400 percent", key = 4, },
            { text = "500 percent", help = "500 percent", key = 5, },
            { text = "700 percent", help = "700 percent", key = 7, },
            { text = "1000 percent", help = "1000 percent", key = 10, },
            { text = "25x", help = "25x", key = 25, },
            { text = "I want lagg", help = "100x", key = 100, },
        },
    },
    {
        default = 1,
        label = "All Factions",
        help = "When enabled, all players start with 4 ACUs, one for each faction",
        key = 'opt_FinalRushAllFactions',
        pref = 'opt_FinalRushAllFactions',
        values = {
            { text = "Enabled", help = "Each player gets 4 ACUs", key = 1, },
            { text = "Disabled", help = "Each player only gets 1 ACU", key = 0, },
        }
    },
    {
        default = 1,
        label = "Team Bonus - HP Reduction",
        help = "Affects both survival modes. Make it easier for one team to improve balance. Decreases the HP of the incoming enemy units for one team by the selected percentage.",
        key = 'opt_FinalRushTeamBonusHP',
        pref = 'opt_FinalRushTeamBonusHP',
        values = {
            { text = "None", help = "None", key = 0 },
            { text = "Top team, 2 percent", help = "The top team gets less strong enemy units", key = 2 },
            { text = "Top team, 5 percent", help = "The top team gets less strong enemy units", key = 5 },
            { text = "Top team, 10 percent", help = "The top team gets less strong enemy units", key = 10 },
            { text = "Top team, 15 percent", help = "The top team gets less strong enemy units", key = 15 },
            { text = "Top team, 20 percent", help = "The top team gets less strong enemy units", key = 20 },
            { text = "Top team, 25 percent", help = "The top team gets less strong enemy units", key = 25 },
            { text = "Top team, 30 percent", help = "The top team gets less strong enemy units", key = 30 },
            { text = "Top team, 35 percent", help = "The top team gets less strong enemy units", key = 35 },
            { text = "Top team, 40 percent", help = "The top team gets less strong enemy units", key = 40 },
            { text = "Top team, 50 percent", help = "The top team gets less strong enemy units", key = 50 },
            { text = "Top team, 60 percent", help = "The top team gets less strong enemy units", key = 60 },
            { text = "Top team, 75 percent", help = "The top team gets less strong enemy units", key = 75 },
            { text = "Top team, 90 percent", help = "The top team gets less strong enemy units", key = 90 },
            { text = "Top team, 95 percent", help = "The top team gets less strong enemy units", key = 95 },
            { text = "Bottom team, 2 percent", help = "The bottom team gets less strong enemy units", key = -2 },
            { text = "Bottom team, 5 percent", help = "The bottom team gets less strong enemy units", key = -5 },
            { text = "Bottom team, 10 percent", help = "The bottom team gets less strong enemy units", key = -10 },
            { text = "Bottom team, 15 percent", help = "The bottom team gets less strong enemy units", key = -15 },
            { text = "Bottom team, 20 percent", help = "The bottom team gets less strong enemy units", key = -20 },
            { text = "Bottom team, 25 percent", help = "The bottom team gets less strong enemy units", key = -25 },
            { text = "Bottom team, 30 percent", help = "The bottom team gets less strong enemy units", key = -30 },
            { text = "Bottom team, 35 percent", help = "The bottom team gets less strong enemy units", key = -35 },
            { text = "Bottom team, 40 percent", help = "The bottom team gets less strong enemy units", key = -40 },
            { text = "Bottom team, 50 percent", help = "The bottom team gets less strong enemy units", key = -50 },
            { text = "Bottom team, 60 percent", help = "The bottom team gets less strong enemy units", key = -60 },
            { text = "Bottom team, 75 percent", help = "The bottom team gets less strong enemy units", key = -75 },
            { text = "Bottom team, 90 percent", help = "The bottom team gets less strong enemy units", key = -90 },
            { text = "Bottom team, 95 percent", help = "The bottom team gets less strong enemy units", key = -95 },
        },
    },
    {
        default = 1,
        label = "Team Bonus - Reclaim",
        help = "Affects both survival modes. Make it easier for one team to improve balance. The percentage is applied as bonus to the auto reclaim. If the auto reclaim setting is 50 percent and the bonus is 50, the team will get 75 percent.",
        key = 'opt_FinalRushTeamBonusReclaim',
        pref = 'opt_FinalRushTeamBonusReclaim',
        values = {
            { text = "None", help = "None", key = 0 },
            { text = "Top team, 2 percent", help = "The top team gets more auto reclaim", key = 2 },
            { text = "Top team, 5 percent", help = "The top team gets more auto reclaim", key = 5 },
            { text = "Top team, 10 percent", help = "The top team gets more auto reclaim", key = 10 },
            { text = "Top team, 15 percent", help = "The top team gets more auto reclaim", key = 15 },
            { text = "Top team, 20 percent", help = "The top team gets more auto reclaim", key = 20 },
            { text = "Top team, 25 percent", help = "The top team gets more auto reclaim", key = 25 },
            { text = "Top team, 30 percent", help = "The top team gets more auto reclaim", key = 30 },
            { text = "Top team, 50 percent", help = "The top team gets more auto reclaim", key = 50 },
            { text = "Top team, 75 percent", help = "The top team gets more auto reclaim", key = 75 },
            { text = "Top team, 100 percent", help = "The top team gets more auto reclaim", key = 100 },
            { text = "Top team, 150 percent", help = "The top team gets more auto reclaim", key = 150 },
            { text = "Top team, 200 percent", help = "The top team gets more auto reclaim", key = 200 },
            { text = "Bottom team, 2 percent", help = "The bottom team gets more auto reclaim", key = -2 },
            { text = "Bottom team, 5 percent", help = "The bottom team gets more auto reclaim", key = -5 },
            { text = "Bottom team, 10 percent", help = "The bottom team gets more auto reclaim", key = -10 },
            { text = "Bottom team, 15 percent", help = "The bottom team gets more auto reclaim", key = -15 },
            { text = "Bottom team, 20 percent", help = "The bottom team gets more auto reclaim", key = -20 },
            { text = "Bottom team, 25 percent", help = "The bottom team gets more auto reclaim", key = -25 },
            { text = "Bottom team, 30 percent", help = "The bottom team gets more auto reclaim", key = -30 },
            { text = "Bottom team, 50 percent", help = "The bottom team gets more auto reclaim", key = -50 },
            { text = "Bottom team, 75 percent", help = "The bottom team gets more auto reclaim", key = -75 },
            { text = "Bottom team, 100 percent", help = "The bottom team gets more auto reclaim", key = -100 },
            { text = "Bottom team, 150 percent", help = "The bottom team gets more auto reclaim", key = -150 },
            { text = "Bottom team, 200 percent", help = "The bottom team gets more auto reclaim", key = -200 },
        },
    },
    {
        default = 1,
        label = "Spawn Delay",
        help = "(Survival modes only) Extra time before the first enemies start spawning. Also delays Random Events and Bounty Hunters. Normal difficulty has 6 seconds spawn delay. Very easy has 3 minutes",
        key = 'opt_FinalRushSpawnDelay',
        pref = 'opt_FinalRushSpawnDelay',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "None", help = "None", key = 0, },
            { text = "10 seconds (standard)", help = "10 seconds (standard)", key = 10, },
            { text = "30 seconds", help = "30 seconds", key = 30, },
            { text = "1 minute", help = "1 minute", key = 60, },
            { text = "2 minutes", help = "2 minutes", key = 120, },
            { text = "3 minutes", help = "3 minutes", key = 180, },
            { text = "5 minutes", help = "5 minutes", key = 300, },
            { text = "7 minutes", help = "7 minutes", key = 420, },
            { text = "10 minutes", help = "10 minutes", key = 600, },
            { text = "15 minutes", help = "15 minutes", key = 900, },
            { text = "24 hours", help = "Welcome to SimCity", key = 86400, },
        },
    },
    {
        default = 1,
        label = "Auto Reclaim",
        help = "If enabled, when you kill a unit it will not leave a wreck, and you will get a fraction of its mass and energy cost",
        key = 'opt_FinalRushAutoReclaim',
        pref = 'opt_FinalRushAutoReclaim',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "Disabled (Wreckages On)", help = "Disabled (Wreckages appear on the map with their usual reclaim value)", key = 0, },
            { text = "Fixed 25 percent", help = "Fixed 25 percent", key = 25, },
            { text = "Fixed 50 percent", help = "Fixed 50 percent", key = 50, },
            { text = "Fixed 75 percent", help = "Fixed 75 percent", key = 75, },
            { text = "Fixed 100 percent", help = "Fixed 100 percent", key = 100, },
            { text = "Decreasing 10 percent", help = "10 percent at the start, linearly decreasing to 0 at minute 60", key = -10, },
            { text = "Decreasing 15 percent", help = "15 percent at the start, linearly decreasing to 0 at minute 60", key = -15, },
            { text = "Decreasing 20 percent", help = "20 percent at the start, linearly decreasing to 0 at minute 60", key = -20, },
            { text = "Decreasing 30 percent", help = "30 percent at the start, linearly decreasing to 0 at minute 60", key = -30, },
            { text = "Decreasing 40 percent", help = "40 percent at the start, linearly decreasing to 0 at minute 60", key = -40, },
            { text = "Decreasing 45 percent", help = "45 percent at the start, linearly decreasing to 0 at minute 60", key = -45, },
            { text = "Decreasing 50 percent (standard)", help = "50 percent at the start, linearly decreasing to 0 at minute 60", key = -50, },
            { text = "Decreasing 55 percent", help = "55 percent at the start, linearly decreasing to 0 at minute 60", key = -55, },
            { text = "Decreasing 60 percent", help = "60 percent at the start, linearly decreasing to 0 at minute 60", key = -60, },
            { text = "Decreasing 70 percent", help = "70 percent at the start, linearly decreasing to 0 at minute 60", key = -70, },
            { text = "Decreasing 80 percent", help = "80 percent at the start, linearly decreasing to 0 at minute 60", key = -80, },
            { text = "Decreasing 100 percent", help = "100 percent, linearly decreasing to 0 at minute 60", key = -100, },
            { text = "Decreasing 125 percent", help = "125 percent, linearly decreasing to 0 at minute 60", key = -125, },
            { text = "Decreasing 150 percent", help = "150 percent, linearly decreasing to 0 at minute 60", key = -150, },
            { text = "Decreasing 200 percent", help = "200 percent, linearly decreasing to 0 at minute 60", key = -200, },
            { text = "Fixed over 9000 percent", help = "You know you want it", key = 9001, },
        },
    },
    {
        default = 1,
        label = "Health Increase",
        help = "(Survival modes only) Determines how much extra health the enemy units that spawn in get for every 100 seconds since units of that type started spawning. 25 percent for normal difficulty",
        key = 'opt_FinalRushHealthIncrease',
        pref = 'opt_FinalRushHealthIncrease',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "None", help = "None", key = 0, },
            { text = "2 percent", help = "2 percent for every 100 seconds", key = 0.02, },
            { text = "5 percent", help = "5 percent for every 100 seconds", key = 0.05, },
            { text = "10 percent", help = "10 percent for every 100 seconds", key = 0.1, },
            { text = "12.5 percent", help = "12.5 percent for every 100 seconds", key = 0.125, },
            { text = "15 percent", help = "15 percent for every 100 seconds", key = 0.15, },
            { text = "17.5 percent (standard)", help = "17.5 percent for every 100 seconds", key = 0.175, },
            { text = "20 percent", help = "20 percent for every 100 seconds", key = 0.2, },
            { text = "22.5 percent", help = "22.5 percent for every 100 seconds", key = 0.225, },
            { text = "25 percent", help = "25 percent for every 100 seconds", key = 0.25, },
            { text = "27.5 percent", help = "27.5 percent for every 100 seconds", key = 0.275, },
            { text = "30 percent", help = "30 percent for every 100 seconds", key = 0.3, },
            { text = "50 percent", help = "50 percent for every 100 seconds", key = 0.5, },
            { text = "100 percent", help = "100 percent for every 100 seconds", key = 1, },
            { text = "200 percent", help = "200 percent for every 100 seconds", key = 2, },
            { text = "300 percent", help = "300 percent for every 100 seconds", key = 3, },
            { text = "400 percent", help = "400 percent for every 100 seconds", key = 4, },
            { text = "500 percent", help = "500 percent for every 100 seconds", key = 5, },
            { text = "Bitcoin price", help = "1000 percent for every 100 seconds", key = 10, },
        },
    },
    {
        default = 1,
        label = "Random Event Frequency",
        help = "(Survival modes only) When enabled, from time to time random events will happen. Mostly these are spawning of special enemy units, such as bombers, artillery and destroyers. Normal difficulty is 70 seconds",
        key = 'opt_FinalRushRandomEvents',
        pref = 'opt_FinalRushRandomEvents',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key =-1337, },
            { text = "No random evensts", help = "No random evensts", key = 0, },
            { text = "Every 10 minutes", help = "Every 10 minutes", key = 600, },
            { text = "Every 5 minutes", help = "Every 5 minutes", key = 300, },
            { text = "Every 2 minutes", help = "Every 2 minutes", key = 120, },
            { text = "Every 90 seconds", help = "Every 90 seconds", key = 90, },
            { text = "Every 70 seconds (standard)", help = "Every 70 seconds (standard)", key = 70, },
            { text = "Every minute", help = "Every minute", key = 60, },
            { text = "Every 45 seconds", help = "Every 45 seconds", key = 45, },
            { text = "Every 30 seconds", help = "Every 30 seconds", key = 30, },
            { text = "Every 20 seconds", help = "Every 20 seconds", key = 20, },
            { text = "Every 5 seconds", help = "Leeroy Jenkins", key = 5, },
        },
    },
    {
        default = 1,
        label = "Event Notifications",
        help = "(Survival modes only) When enabled, you will get warnings whenever a Random Event happens (ie bombers incoming) or when Bounty Hunters spawn.",
        key = 'opt_FinalRushEventNotifications',
        pref = 'opt_FinalRushEventNotifications',
        values = {
            { text = "Enabled", help = "Enabled", key = 1, },
            { text = "Disabled", help = "Disabled", key = 0, },
        },
    },
    {
        default = 1,
        label = "Killable Transports",
        help = "Allow killing the transports bringing in the units",
        key = 'opt_FinalRushKillableTransports',
        pref = 'opt_FinalRushKillableTransports',
        values = {
            { text = "Enabled", help = "Enabled (transports can be killed)", key = 0, },
            { text = "Disabled", help = "Disabled (transports can not be killed)", key = 1, },
        },
    },
    {
        default = 1,
        label = "ACU Hiding",
        help = "Allow or prevent ACU hiding in the water and hills",
        key = 'opt_FinalRushWaterKillsACUs',
        pref = 'opt_FinalRushWaterKillsACUs',
        values = {
            { text = "Prevent hiding", help = "ACUs cannot hide", key = 0, },
            { text = "Allow hiding", help = "ACUs can hide", key = 1, },
        },
    },
    {
        default = 1,
        label = "Bounty Hunter Spawn Delay",
        help = "Time before the first Bounty Hunters start spawning. Compounds with the general Spawn Delay option. Normal difficulty is 22 minutes",
        key = 'opt_FinalRushHunterDelay',
        pref = 'opt_FinalRushHunterDelay',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "None", help = "None", key = 0, },
            { text = "5 minutes", help = "5 minutes", key = 300, },
            { text = "7 minutes", help = "7 minutes", key = 420, },
            { text = "10 minutes", help = "10 minutes", key = 600, },
            { text = "15 minutes", help = "15 minutes", key = 900, },
            { text = "18 minutes", help = "18 minutes", key = 18 * 60, },
            { text = "20 minutes", help = "20 minutes", key = 1200, },
            { text = "22 minutes", help = "22 minutes", key = 22 * 60, },
            { text = "24 minutes", help = "24 minutes", key = 24 * 60, },
            { text = "30 minutes", help = "30 minutes", key = 1800, },
            { text = "40 minutes", help = "40 minutes", key = 2400, },
            { text = "50 minutes", help = "50 minutes", key = 3000, },
            { text = "60 minutes", help = "60 minutes", key = 3600, },
        },
    },
    {
        default = 1,
        label = "Bounty Hunter Frequency",
        help = "(Survival modes only) When enabled, from time to time Bounty Hunters (an ACU and a few SACUs) will hunt the players. Normal difficulty is 5 minutes",
        key = 'opt_FinalRushHunters',
        pref = 'opt_FinalRushHunters',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "No Bounty Hunters", help = "No Bounty Hunters", key = 0, },
            { text = "Every 20 minutes", help = "Every 20 minutes", key = 1200, },
            { text = "Every 10 minutes", help = "Every 10 minutes", key = 600, },
            { text = "Every 7 minutes", help = "Every 7 minutes", key = 420, },
            { text = "Every 5 minutes", help = "Every 5 minutes", key = 300, },
            { text = "Every 3 minutes", help = "Every 3 minutes", key = 180, },
            { text = "Every 2 minutes", help = "Every 2 minutes", key = 120, },
            { text = "Every minute", help = "Every minute", key = 60, },
            { text = "Every 5 seconds", help = "Because I'm worth it", key = 5, },
        },
    },
    {
        default = 1,
        label = "Enemy T2 MMLs",
        help = "(Survival modes only) T2 MMLs",
        key = 'opt_t2tml',
        pref = 'opt_t2tml',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "Enabled (standard)", help = "Enabled (standard)", key = 0, },
            { text = "Disabled", help = "Disabled", key = 1, },
        },
    },
    {
        default = 1,
        label = "Enemy Mobile T3 Artillery",
        help = "(Survival modes only) Mobile T3 Artillery",
        key = 'opt_t3arty',
        pref = 'opt_t3arty',
        values = {
            { text = "Difficulty preset", help = "Automatically pick a value based on the selected difficulty", key = -1337, },
            { text = "Enabled (standard)", help = "Enabled (standard)", key = 0, },
            { text = "Disabled", help = "Disabled", key = 1, },
        },
    },
    {
        default = 1,
        label = "Player Air",
        help = "The degree to which air should be enabled for the players",
        key = 'opt_FinalRushAir',
        pref = 'opt_FinalRushAir',
        values = {
            { text = "Disabled", help = "No air units at all", key = 0, },
            { text = "Scouts and Transports", help = "Scouts and transports only", key = 1, },
            { text = "Enabled", help = "All air units are enabled. NOTE: the incoming waves do NOT contain AA even with this option.", key = 2, },
        },
    },
    {
        default = 1,
        label = "Player Nukes and T3 Arty",
        help = "If players should be able to build nukes, T3 arty and T4 arty",
        key = 'opt_FinalRushNukesAndArty',
        pref = 'opt_FinalRushNukesAndArty',
        values = {
            { text = "Disabled", help = "Players cannot build nukes, T3 arty and T4 arty", key = 0, },
            { text = "Enabled", help = "No build restrictions for nukes, T3 arty and T4 arty on top of what is selected in the lobby", key = 1, },
        },
    },
    {
        default = 1,
        label = "Player Tech Delay",
        help = "Players start with only tech 1. Higher tech tiers get unlocked at the specified interval. This does not effect the spawned enemy units.",
        key = 'opt_timeunlocked',
        pref = 'opt_timeunlocked',
        values = {
            { text = "Disabled", help = "Disabled", key = 0, },
            { text = "1 minute", help = "1 minute", key = 60, },
            { text = "2 minutes", help = "2 minutes", key = 120, },
            { text = "3 minutes", help = "3 minutes", key = 180, },
            { text = "5 minutes", help = "5 minutes", key = 300, },
            { text = "10 minutes", help = "10 minutes", key = 600, },
            { text = "15 minutes", help = "15 minutes", key = 900, },
            { text = "20 minutes", help = "20 minutes", key = 1200, },
            { text = "24 hours", help = "Who needs tech anyway. Such hipsters", key = 86400, },
        },
    },
    {
        default = 10,
        label = "Prebuilt Tents",
        help = "Disable or Set the number of Prebuilt Engineering Tents",
        key = 'opt_tents',
        pref = 'opt_tents',
        values = {
            { text = "Disabled", help = "Spawn with NO tents", key = 0, },
            { text = "1", help = "Spawn with ONE tents", key = 1, },
            { text = "2", help = "Spawn with TWO tents", key = 2, },
            { text = "3", help = "Spawn with THREE tents", key = 3, },
            { text = "4", help = "Spawn with FOUR tents", key = 4, },
            { text = "5", help = "Spawn with FIVE tents", key = 5, },
            { text = "6", help = "Spawn with SIX tents", key = 6, },
            { text = "7", help = "Spawn with SEVEN tents", key = 7, },
            { text = "8", help = "Spawn with EIGHT tents", key = 8, },
            { text = "9", help = "Spawn with NINE tents", key = 9, },
        },
    }
};
